#!/usr/bin/env bash
#Bash script that displays numbers from 1 to 100.
for i in {1..100}
do
	if [ $(($i % 3)) -eq 0 ] && [ $(($i % 5)) -eq 0 ]
	then
		echo "FizzBuzz"
	fi
        if [ $(($i % 3)) -eq 0 ]
        then
                echo "Fizz"
        fi
        if [ $(($i % 5)) -eq 0 ]
        then
                echo "Buzz"
        fi

done
