#!/usr/bin/env bash
#Bash script that displays the content of the file /etc/passwd.

#Your script should only display:

#username
#user id
#Home directory path for the user
xxx=':'
while xxx=: read -r username x uid gid info homedir shell; do
    echo "$username:$uid:$homedir"
done </etc/passwd
