#!/usr/bin/env bash
#Write a Bash script that displays the content of the file /etc/passwd.

#Your script should only display:

#username
#user id
#Home directory path for the user
IFS=":"
while read -ra word
do
	echo "The user ${word[0]} is part of the ${word[3]} gang, lives in ${word[5]} and rides ${word[6]}. ${word[2]}'s place is protected by the passcode ${word[1]}, more info about the user here: ${word[4]}"
done < /etc/passwd
