#!/usr/bin/env bash
face_ip=$( sudo awk '/facebook/ { print $2 }' ./etc/hosts )
local_ip=$( sudo awk '/localhost/ { print $2 }' ./etc/hosts )

if [[ -n $face_ip ]]; then
    sudo sed -i.back "s/$face_ip/8.8.8.8/" ./etc/hosts
fi
if [[ -n $local_ip ]]; then
    sudo sed -i.back "s/$local_ip/127.0.0.2/" ./etc/hosts
fi
