#!/usr/bin/env bash
# a Bash script that configures an Ubuntu server with the below requirements.

# Requirements:

# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.
# The checker is running on Docker, so make sure to read

face_ip=$( sudo awk '/facebook/ { print $2 }' ./etc/hosts )
local_ip=$( sudo awk '/localhost/ { print $2 }' ./etc/hosts )

if [[ -n $face_ip ]]; then
    sudo sed -i.back "s/$face_ip/8.8.8.8/" ./temp_file
fi
if [[ -n $local_ip ]]; then
    sudo sed -i.back "s/$local_ip/127.0.0.2/" ./temp_file
fi
sudo cp -f temp_file ./etc/hosts
