#!/usr/bin/env bash
# a Bash script that configures an Ubuntu server with the below requirements.

# Requirements:

# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

cp /etc/hosts temp_file

face_ip=$( sudo awk '/facebook.com/ { print $1 }' /etc/hosts )
local_ip=$( sudo awk '/localhost/ { print $1 }' /etc/hosts )

if [[ -n $face_ip ]]; then
    sed -i.back "s/$face_ip/8.8.8.8/" ./temp_file
else
    echo "8.8.8.8       facebook.com" >> ./temp_file
fi

if [[ -n $local_ip ]]; then
    sed -i "s/$local_ip/127.0.0.2 /" ./temp_file
else
    echo -e "127.0.0.2\tlocalhost " >> ./temp_file
fi

sudo cp -f temp_file /etc/hosts
