#!/usr/bin/env bash
#let’s configure it to our needs so that you can connect to a server without typing a password. 
#Share your SSH client configuration in your answer file.
Host *
    PasswordAuthentication no
    IdentityFile ~/.ssh/school
